# Generated by Django 3.1.7 on 2021-04-08 15:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('my_testApp', '0004_auto_20210408_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 8, 15, 57, 19, 147476, tzinfo=utc)),
        ),
    ]
