# Generated by Django 3.1.7 on 2021-04-08 15:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('data', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 4, 8, 15, 48, 50, 634769, tzinfo=utc))),
                ('title', models.CharField(max_length=50)),
            ],
        ),
    ]
