# Generated by Django 3.1.7 on 2021-04-10 12:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0003_auto_20210408_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 10, 12, 48, 6, 920580, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 10, 12, 48, 6, 920580, tzinfo=utc)),
        ),
    ]
